### ISSUE TITLE
Feature request: filter to add keys

### ISSUE THREAD

**Issue by nicomollet** [Ipstenu/ban-hammer#6]
Hello

I found a use case where I would like to add (with a filter) my own list of keys to ban.
Can this be added to the plugin?

Thank you

**Comment by Ipstenu** [comment]
But … why? The plug-in turns the disallowed list into a block list. What’s the filter for when you just add the blocks in?

I feel like I’m missing the use case here.

**Comment by nicomollet** [comment]
My use case is: I manage many sites, all with the same banned emails. 
Maintaining the list for every site could be avoided by hard coding the common list in a filter in a plugin.
I hope you understand what I mean :)
